### ISSUE TITLE
Problems with spleeter

### ISSUE THREAD

**Issue by fosfrancesco** [zhaojw1998/Beat-Transformer#15]
Hello, thanks for the great work!

I'm trying to run the pretrained models on my own songs following the colab instructions, but I am encountering a problem with spleeter when I run:
```
x = separator.separate(waveform)
x = np.stack([np.dot(np.abs(np.mean(separator._stft(x[key]), axis=-1))**2, mel_f) for key in x])
```
The error is:
```
'Separator' object has no attribute '_stft
```

I've looked into the spleeter repo, but I don't find any instance of this _stft attribute. Do you have any suggestions?

Thank you,

Francesco

**Comment by zhaojw1998** [comment]
Hi Francesco,

It looks like Spleeter has updated their code based in the latest 2.4.0 version (updated July 10 2023). Could you have a try with an older 2.3.2 version (pip install spleeter==2.3.2) and see if it could work? 

Also, the latest python 3.10 version (default in Colab) seems incompatible with madmom 0.16. According to [this thread](https://github.com/CPJKU/madmom/issues/502), this problem should be fixed in the madmom 0.17 version.

**Comment by fosfrancesco** [comment]
Thank you for the prompt answer! 
I can confirm that the latest version of madmom works. For the spleeter version I will be able to check it next week since I won't have a computer until then to test it. I will update this thread then.

Have a great day!

**Comment by zhaojw1998** [comment]
Hi Francesco,

Thanks for your interest in our work! Here is some follow-up message if you are still working on that issue:

In the Colab notwbook, Spleeter 2.3.2 version is required and madmom has to be built from source (rather than pip). 
* Install Spleeter:
```
!pip install spleeter==2.3.2
```
* Install madmom:
```
!git clone --recursive https://github.com/CPJKU/madmom.git && mv madmom tmp && mv tmp/* . && rm -rf tmp
!python setup.py develop --user
```
Here are more details if you are interested:
* For Spleeter, we rely on the _stft() method (discarded since version 2.4.0) to retrieve the demixed *spectrogram*, which will be used for beat tracking in the next stage. The stft method from librosa should also work if you prefer the latest Spleeter version, though I have not tested yet. 
* For madmom, the 0.16.1 version from pip has something incompatible with Python 3.10, while an updated 0.17 version solves the problem but can only be built from source.

I have updated the Colab notebook and hopefully it should work fine at the moment. Feel free to let me know if you have any questions!

**Comment by fosfrancesco** [comment]
Thank you for your help, it is working perfectly now!
Feel free to close this issue.
