### ISSUE TITLE
Minor oversight in implementation

### ISSUE THREAD

**Issue by sedthh** [zhaojw1998/Beat-Transformer#18]
This is really great stuff! Just wanted to point out a small issue in `DilatedTransformerLayer.py`

I think you meant
` self.kv_roll(k[:, 7: 8], layer, padding_value=0, shift=2)  `
instead of  https://github.com/zhaojw1998/Beat-Transformer/blob/94f20e19eadb742ca4e701af972a084cbf7be7dd/code/DilatedTransformerLayer.py#L42
Also in https://github.com/zhaojw1998/Beat-Transformer/blob/94f20e19eadb742ca4e701af972a084cbf7be7dd/code/DilatedTransformerLayer.py#L115 there is no definition for x_ for when the DilatedTransformerLayer is not `norm_first`

**Comment by zhaojw1998** [comment]
Thanks very much for the kind comments!

Yes, in Line 42, it should be `k[:, 7: 8]` rather than `k[:, 6: 7]`. We had this bug during model training so we keep it to fit the checkpoints and to reproduce the reported results. I will add a comment in the code reminding this.

For Line 115, I will push an updated version correcting the code. Thanks again for pointing this issue!
