### ISSUE TITLE
question about the DBNBeatTrackingProcessor、DBNDownBeatTrackingProcessor

### ISSUE THREAD

**Issue by tricky61** [zhaojw1998/Beat-Transformer#9]
In the training process, DBNBeatTrackingProcessor、DBNDownBeatTrackingProcessor are not used, the loss is calculated by the Demixed_DilatedTransformerModel and ground truth. but in the inference process, after the Demixed_DilatedTransformerModel, the actvition is passed to DBNBeatTrackingProcessor and DBNDownBeatTrackingProcessor. 
I think there is a mismatch between training and inference. but seems all the beat prediction open source project use DBNBeatTrackingProcessor and DBNDownBeatTrackingProcessor after the activation? Have you tried simple use of the activation as the prediction mark?

**Comment by zhaojw1998** [comment]
> In the training process, DBNBeatTrackingProcessor、DBNDownBeatTrackingProcessor are not used, the loss is calculated by the Demixed_DilatedTransformerModel and ground truth. but in the inference process, after the Demixed_DilatedTransformerModel, the actvition is passed to DBNBeatTrackingProcessor and DBNDownBeatTrackingProcessor. I think there is a mismatch between training and inference. but seems all the beat prediction open source project use DBNBeatTrackingProcessor and DBNDownBeatTrackingProcessor after the activation? Have you tried simple use of the activation as the prediction mark?

Usually, when training a beat-tracking model, the training target is to predict beat/downbeat _activation_ from an input spectrogram. The _activation_ can be regarded as a time sequence of likelihood (with continuous values in [0, 1]), representing the model's certainty about how likely each timestep is a beat/downbeat.

Based on the _activation_ predicted by our model, at inference time, we additionally need a post-processing step to make a binary decision (discrete 0 and 1) at each timestep. Previous post-processing methods include thresholding (e.g., each timestep whose _activation_ > 0.6 is a beat/downbeat), and peak-picking (i.e., each timestep whose _activation_ is higher than both neighbors is a beat/downbeat). Unfortunately, however, the _activation_ predicted by our model tends to be very noisy so neither thresholding nor peak-picking yields satisfactory performance. That is why we introduce DBN(Down)BeatTrackingProcessor here as the post-processor. It makes a global decision to determine discrete beat/downbeat and non-beat events based on dynamic programming. The DBNBeatTrackingProcessor and DBNDownBeatTrackingProcessor are not included in the training target because they are not differentiable (no gradient).

**Comment by tricky61** [comment]
> 
yes. I find most of the beat predict work use DBN as the postprocess.
I will close the issue.

**Comment by tricky61** [comment]
another question.
the spleeter will split the music into vocals、accompaniment, piano、vocals、bass、drums、other according to the stems.
have you tried exclude vocals for the prediction. 
because the vocals are mainly singing. the singing beat prediction and music prediction seems different in this paper: https://arxiv.org/abs/2208.14578.

**Comment by zhaojw1998** [comment]
> another question. the spleeter will split the music into vocals、accompaniment, piano、vocals、bass、drums、other according to the stems. have you tried exclude vocals for the prediction. because the vocals are mainly singing. the singing beat prediction and music prediction seems different in this paper: https://arxiv.org/abs/2208.14578.

I did not try excluding vocals in experiments and I don't think it would be helpful. Vocal is anyway an important integrative part of the whole piece. Our purpose of demixing is to explore how vocal cooperates with other stems. We believe such cooperation is a useful metrical hint.
